Claims Management App/mdapipkg/mdapipkg/unpackaged/unpackaged/objects/Claim__c.object
<CustomObject>
    <description>Holds primary claim information.</description>
    <fields>
        <fullName>Claimant__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Claimant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policy_Coverage__c</fullName>
        <label>Policy Coverage</label>
        <referenceTo>Policy_Coverage__c</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Policy__c</fullName>
        <label>Policy</label>
        <referenceTo>Policy__c</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Claims Management App/mdapipkg/mdapipkg/unpackaged/unpackaged/objects/Policy__c.object
<CustomObject>
    <description>Holds insurance policy information.</description>
    <fields>
        <fullName>Policy_Holder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Policy Holder</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Policies</relationshipLabel>
        <relationshipName>Policies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policy_Number__c</fullName>
        <formula>LEFT(TEXT(Policy_Type__c),1) + Policy_Number_Block__c</formula>
        <label>Policy Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_Type__c</fullName>
        <label>Policy Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>General Liability</fullName>
                </value>
                <value>
                    <fullName>Umbrella</fullName>
                </value>
                <value>
                    <fullName>Renters</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Claims Management App/mdapipkg/mdapipkg/unpackaged/unpackaged/objects/Policy_Coverage__c.object
<CustomObject>
    <description>Contains coverage-level information on a policy, such as limits and reserves.</description>
    <fields>
        <fullName>Coverage_Type__c</fullName>
        <label>Coverage Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Loss of Use</fullName>
                </value>
                <value>
                    <fullName>Medical Payments to Others</fullName>
                </value>
                <value>
                    <fullName>Personal Liability</fullName>
                </value>
                <value>
                    <fullName>Personal Property</fullName>
                </value>
                <value>
                    <fullName>Personal Property Replacement Cost</fullName>
                </value>
                <value>
                    <fullName>Scheduled Personal Property</fullName>
                </value>
                <value>
                    <fullName>Special Computer Coverage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Policy_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Policy Number</label>
        <referenceTo>Policy__c</referenceTo>
        <relationshipLabel>Policy Coverages</relationshipLabel>
        <relationshipName>Policy_Coverages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Policy Coverage</label>
    <nameField>
        <label>Policy Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Coverages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Claims Management App/force-app/main/default/classes/DataFactory.cls
public class DataFactory {
    /**
     * Creates a number of contacts according to the passed argument, and returns the IDs of the records.
     * @param  intNumberOfContacts Integer
     * @return Returns List<ID> 
     */
    public static List<ID> createContacts(Integer intNumberOfContacts){
        List<Contact> listContacts = new List<Contact>();
        List<ID> listContactIDs = new List<ID>();
        
        for (Integer counter = 0; counter < intNumberOfContacts; counter++) {
            Contact c = new Contact();
            c.FirstName = 'First Name: ' + counter;
            c.LastName = 'Last Name: ' + counter;
            listContacts.add(c);
        }
        
        insert listContacts;
        
        for (Contact con : listContacts) {
            listContactIDs.add(con.Id);
        }
        
        return listContactIDs;
    }
    
    public static List<ID> createPolicies(List<ID> policyHolderIDs, Integer intNumberOfPolicies){
        List<Policy__c> policiesToInsert = new List<Policy__c>();
        Integer polHolderIDCounter = 0;
        List<ID> policyIDs = new List<ID>();
        
        for (Integer counter = 0; counter < intNumberOfPolicies; counter++) {
            if (counter >= policyHolderIDs.size()) {
                polHolderIDCounter = 0;
            }
            
            Policy__c policyToInsert = new Policy__c();
            policyToInsert.Policy_Holder__c = policyHolderIDs.get(polHolderIDCounter);
            policyToInsert.Policy_Type__c = 'Renters';
            policyToInsert.Name = 'Renters Policy TEST: ' + counter;
            policiesToInsert.add(policyToInsert);
            
            polHolderIDCounter++;
        }
        
        insert policiesToInsert;
        
        for (Policy__c newPolicy : policiesToInsert) {
            policyIDs.add(newPolicy.Id);
        }
        
        return policyIDs;
    }
    
    public static List<ID> createPolicyCoverages(List<ID> policyIDs){
        List<Schema.PicklistEntry> currentCoverageTypes = Schema.Policy_Coverage__c.Coverage_Type__c.getDescribe().getPickListValues();
        List<Policy_Coverage__c> policyCoverages = new List<Policy_Coverage__c>();
        Policy_Coverage__c policyCoverage;
        List<ID> policyCoverageIDs = new List<ID>();
        
        for (ID i : policyIDs) {
            for (Schema.PicklistEntry coverageType : currentCoverageTypes) {
                policyCoverage = new Policy_Coverage__c();
                policyCoverage.Name = 'Coverage ' + coverageType.getLabel() + ' for policy ID ' + i;
                policyCoverage.Coverage_Type__c = coverageType.getLabel();
                policyCoverage.Limit__c = Decimal.valueOf(Math.random() * 1000).setScale(2);
                policyCoverage.Policy_Number__c = i;
                policyCoverages.add(policyCoverage);
            }
            
        }
        insert policyCoverages;
        
        for (Policy_Coverage__c pc : policyCoverages) {
            policyCoverageIDs.add(pc.Id);
        }
        
        return policyCoverageIDs;
    }
    
    public static List<ID> createClaims(List<ID> policyIDs){
        List<Policy__c> policies  = [SELECT Id, Policy_Holder__c, (SELECT Id FROM Policy_Coverages__r) FROM Policy__c WHERE Id IN :policyIDs];
        List<Claim__c> claims = new List<Claim__c>();
        List<ID> claimIDs = new List<ID>();
        Claim__c claim;
        for (Policy__c pol : policies) {
            for (Policy_Coverage__c coverage : pol.Policy_Coverages__r) {
                claim = new Claim__c();
                claim.Policy__c = pol.Id;
                claim.Claimant__c = pol.Policy_Holder__c;
                claim.Policy_Coverage__c = coverage.Id;
                claims.add(claim);
            }
        }
        
        insert claims;
        
        for (Claim__c c : claims) {
            claimIDs.add(c.Id);
        }
        
        return claimIDs;
    }
}